"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['NFT Auto.py']
DATA_FILES = []
OPTIONS = {
    "includes": [
        "PyQt6.QtGUi",
        "PyQt6.QtWidgets",
        "PyQt6.QtCore",
        "PIL.Image",
        "PIL.ImageQt",
        "numpy"
        "sys",
        "os",
        "time",
        "./resource_rc.py", 
        "./ui.py"
    ],
    "iconfile": "./resources/icon.png",
    "resources": "./resources",
    
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    py_modules=[]
)
